INSERT INTO "public"."questions" ("id", "text", "category", "cf_pakar", "keywords") VALUES
(1, 'Seberapa suka Anda memperbaiki barang yang rusak?', 'R', 0.9, 'repair, mechanic, maintain, service, fix'),
(2, 'Seberapa suka Anda bekerja dengan alat atau mesin?', 'R', 1.0, 'machine, equipment, operate, engineer, electric, technician'),
(3, 'Seberapa suka Anda bekerja di luar ruangan dalam waktu lama?', 'R', 0.75, 'agricultur, farm, forest, environment, construct, drive'),
(4, 'Seberapa suka Anda melakukan aktivitas seperti merakit atau membangun sesuatu?', 'R', 0.9, 'construct, assemble, build, architect, install'),
(5, 'Seberapa suka Anda melakukan pekerjaan yang membutuhkan kekuatan fisik?', 'R', 0.7, 'physical, labor, helper, worker, athlet'),
(6, 'Seberapa suka Anda mencari tahu bagaimana sesuatu bekerja?', 'I', 0.8, 'system, computer, technology, engineer, science'),
(7, 'Seberapa suka Anda melakukan eksperimen atau penelitian?', 'I', 1.0, 'research, scientist, lab, clinic, experiment'),
(8, 'Seberapa suka Anda memecahkan soal atau masalah yang kompleks?', 'I', 0.9, 'analyst, economist, planner, math, logic'),
(9, 'Seberapa suka Anda menganalisis data atau informasi?', 'I', 0.85, 'data, analyst, computer, statistic, information'),
(10, 'Seberapa suka Anda mempelajari ilmu pengetahuan seperti biologi atau fisika?', 'I', 0.95, 'biolog, physic, medicine, medical, health, science'),
(11, 'Seberapa suka Anda menggambar atau membuat karya seni?', 'A', 1.0, 'draw, paint, artist, design, illustrat, animat'),
(12, 'Seberapa suka Anda menulis cerita atau puisi?', 'A', 0.9, 'writ, author, poet, journal, report, edit'),
(13, 'Seberapa suka Anda terlibat dalam musik atau pertunjukan seni?', 'A', 0.95, 'music, act, direct, dance, radio, video, film'),
(14, 'Seberapa suka Anda mengekspresikan ide secara kreatif?', 'A', 0.8, 'design, creat, commercial, media, fashion, camera'),
(15, 'Seberapa suka Anda bekerja tanpa aturan yang terlalu ketat?', 'A', 0.7, 'freelance, independent, art, entertain, talent'),
(16, 'Seberapa suka Anda membantu orang lain menyelesaikan masalah?', 'S', 0.95, 'therapist, counsel, social, advise, psycholog'),
(17, 'Seberapa suka Anda bekerja dalam tim atau kelompok?', 'S', 0.75, 'coordinate, facilitate, community, human, support'),
(18, 'Seberapa suka Anda melakukan pekerjaan seperti guru, konselor, atau pekerja sosial?', 'S', 1.0, 'teacher, school, educat, counsel, social'),
(19, 'Seberapa suka Anda mendengarkan dan memahami perasaan orang lain?', 'S', 0.9, 'psycholog, psychiatr, mental, clergy, care'),
(20, 'Seberapa suka Anda memberikan bantuan atau perawatan kepada orang lain?', 'S', 0.85, 'nurse, aide, assist, health, care, medical'),
(21, 'Seberapa suka Anda memimpin atau mengarahkan orang lain?', 'E', 1.0, 'manage, supervis, direct, executive, chief'),
(22, 'Seberapa suka Anda terlibat dalam dunia bisnis atau penjualan?', 'E', 0.95, 'sale, market, retail, business, represent, buyer'),
(23, 'Seberapa suka Anda berbicara di depan umum?', 'E', 0.8, 'public, relation, promote, agent, speaker, announc'),
(24, 'Seberapa suka Anda mengambil risiko dalam mencapai tujuan?', 'E', 0.85, 'finance, broker, invest, venture, executive'),
(25, 'Seberapa suka Anda merintis atau membangun usaha sendiri?', 'E', 1.0, 'found, entrepreneur, contract, consult, manage'),
(26, 'Seberapa suka Anda melakukan pekerjaan yang teratur dan terstruktur?', 'C', 0.9, 'admin, organiz, clerk, record, document'),
(27, 'Seberapa suka Anda bekerja dengan data atau angka?', 'C', 0.85, 'account, finance, audit, budget, tax, math'),
(28, 'Seberapa suka Anda mengerjakan sesuatu dengan teliti dan mendetail?', 'C', 0.8, 'examin, inspect, investigat, audit, quality'),
(29, 'Seberapa suka Anda bekerja dengan mengikuti prosedur yang jelas?', 'C', 0.95, 'clerk, assist, attend, compliance, operate'),
(30, 'Seberapa suka Anda melakukan pekerjaan yang rutin dan terorganisir?', 'C', 1.0, 'administer, manage, record, bookkeep, data');