INSERT INTO "public"."questions" ("id", "text", "category", "cf_pakar", "keywords") VALUES
(1, 'Apakah Anda suka memperbaiki barang yang rusak?', 'R', 0.9, 'repair, mechanic, maintain, service, fix'),
(2, 'Apakah Anda tertarik bekerja dengan alat atau mesin?', 'R', 1.0, 'machine, equipment, operate, engineer, electric, technician'),
(3, 'Apakah Anda nyaman bekerja di luar ruangan dalam waktu lama?', 'R', 0.75, 'agricultur, farm, forest, environment, construct, drive'),
(4, 'Apakah Anda menikmati aktivitas seperti merakit atau membangun sesuatu?', 'R', 0.9, 'construct, assemble, build, architect, install'),
(5, 'Apakah Anda tertarik pada pekerjaan yang membutuhkan kekuatan fisik?', 'R', 0.7, 'physical, labor, helper, worker, athlet'),
(6, 'Apakah Anda suka mencari tahu bagaimana sesuatu bekerja?', 'I', 0.8, 'system, computer, technology, engineer, science'),
(7, 'Apakah Anda tertarik melakukan eksperimen atau penelitian?', 'I', 1.0, 'research, scientist, lab, clinic, experiment'),
(8, 'Apakah Anda menikmati memecahkan soal yang kompleks?', 'I', 0.9, 'analyst, economist, planner, math, logic'),
(9, 'Apakah Anda suka menganalisis data atau informasi?', 'I', 0.85, 'data, analyst, computer, statistic, information'),
(10, 'Apakah Anda tertarik pada ilmu pengetahuan seperti biologi atau fisika?', 'I', 0.95, 'biolog, physic, medicine, medical, health, science'),
(11, 'Apakah Anda suka menggambar atau membuat karya seni?', 'A', 1.0, 'draw, paint, artist, design, illustrat, animat'),
(12, 'Apakah Anda menikmati menulis cerita atau puisi?', 'A', 0.9, 'writ, author, poet, journal, report, edit'),
(13, 'Apakah Anda tertarik pada musik atau pertunjukan seni?', 'A', 0.95, 'music, act, direct, dance, radio, video, film'),
(14, 'Apakah Anda suka mengekspresikan ide secara kreatif?', 'A', 0.8, 'design, creat, commercial, media, fashion, camera'),
(15, 'Apakah Anda merasa nyaman bekerja tanpa aturan yang terlalu ketat?', 'A', 0.7, 'freelance, independent, art, entertain, talent'),
(16, 'Apakah Anda suka membantu orang lain menyelesaikan masalah?', 'S', 0.95, 'therapist, counsel, social, advise, psycholog'),
(17, 'Apakah Anda menikmati bekerja dalam tim atau kelompok?', 'S', 0.75, 'coordinate, facilitate, community, human, support'),
(18, 'Apakah Anda tertarik menjadi guru, konselor, atau pekerja sosial?', 'S', 1.0, 'teacher, school, educat, counsel, social'),
(19, 'Apakah Anda suka mendengarkan dan memahami perasaan orang lain?', 'S', 0.9, 'psycholog, psychiatr, mental, clergy, care'),
(20, 'Apakah Anda merasa puas saat bisa membantu orang lain?', 'S', 0.85, 'nurse, aide, assist, health, care, medical'),
(21, 'Apakah Anda suka memimpin atau mengarahkan orang lain?', 'E', 1.0, 'manage, supervis, direct, executive, chief'),
(22, 'Apakah Anda tertarik pada dunia bisnis atau penjualan?', 'E', 0.95, 'sale, market, retail, business, represent, buyer'),
(23, 'Apakah Anda nyaman berbicara di depan umum?', 'E', 0.8, 'public, relation, promote, agent, speaker, announc'),
(24, 'Apakah Anda suka mengambil risiko dalam mencapai tujuan?', 'E', 0.85, 'finance, broker, invest, venture, executive'),
(25, 'Apakah Anda tertarik membangun usaha sendiri?', 'E', 1.0, 'found, entrepreneur, contract, consult, manage'),
(26, 'Apakah Anda menikmati pekerjaan yang teratur dan terstruktur?', 'C', 0.9, 'admin, organiz, clerk, record, document'),
(27, 'Apakah Anda suka bekerja dengan data atau angka?', 'C', 0.85, 'account, finance, audit, budget, tax, math'),
(28, 'Apakah Anda teliti dalam mengerjakan sesuatu?', 'C', 0.8, 'examin, inspect, investigat, audit, quality'),
(29, 'Apakah Anda nyaman mengikuti prosedur yang jelas?', 'C', 0.95, 'clerk, assist, attend, compliance, operate'),
(30, 'Apakah Anda menikmati pekerjaan yang rutin dan terorganisir?', 'C', 1.0, 'administer, manage, record, bookkeep, data');